apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: wxops-core-scm-connection
spec:
  package: ghcr.io/wxops-idp/wxops-core/scm-connection:release-2026-10-09
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
